apiVersion: v1
kind: Service
metadata:
  name: cicd-springboot-service
spec:
  type: NodePort
  selector:
    app: cicd-springboot
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
